version: "3.9"


services:
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash ./start-local.sh
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: 128m
    volumes:
      - ./deploy:/test_shop/deploy
      - ./:/test_shop/
    ports:
      - "8000:8000"

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:15-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

volumes:
  test_shop_backend:
  test_shop_db:
  test_shop_redis: