# Generated by Django 5.0 on 2023-12-21 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
