# Generated by Django 5.0 on 2023-12-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_category_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category",
                to="products.product",
            ),
        ),
    ]
