# Generated by Django 5.0 on 2023-12-21 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_product_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
