# Generated by Django 5.0 on 2023-12-21 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
    ]
